### ISSUE TITLE
gitignore tip

### ISSUE THREAD

**Issue by ekivolowitz** [riverscuomo/new-albums#1]
Hey Rivers, I'm a big fan turned bigger fan after discovering that you're learning to program. I'm not sure how far along you are in your CS education but keep it up! It is incredibly daunting but equally rewarding.

I had one small suggestion that will clean up your repository a bit. [This](https://stackoverflow.com/a/16869074/14382914) StackOverflow post explains what the `__pycache__` is, and it's not needed to version control with git. To ignore it, you can add these two lines sourced from this [python boilerplate gitignore](https://github.com/github/gitignore/blob/main/Python.gitignore) on github.

```
__pycache__/
*.py[cod]
```

The first line will ignore the root level `__pycache__/` folder and any subfolder that matches `__pycache__/`. The second line will ignore any file that ends in either `pyc`, `pyo`, `pyd`.

If you would like, I would be happy do a code review here and there or act as a sounding board for any ideas you have about how to implement something - I'm quite comfortable with Flask and other WSGI/ASGI frameworks, and I'm learning about frontend (React), and deploying on infra (AWS).

My discord name is ekivol#2552 if you want to PM me any qs or code reviews!

**Comment by riverscuomo** [comment]
Thank you. I've done what you suggested and also removed the file already committed with `git rm -r --cached <folder>`. Hopefully I haven't already blown my security by committing the __pycache__ folder.

I would definitely appreciate a code review here and there as I figure out how to share my repositories without exposing secrets. I added an explanation of my hopes and concerns to this repo's README. Please check it out.
