### ISSUE TITLE
Discord invite link expired?

### ISSUE THREAD

**Issue by bitmappergit** [riverscuomo/new-albums#16]
The discord invite link seems to be expired.

**Comment by riverscuomo** [comment]
I just turned it back on. Let me know if it's still not working.
https://discord.gg/mr-rivers-neighborhood

**Comment by colelloa** [comment]
I just tested this, and I believe this issue can now be closed.

**Comment by riverscuomo** [comment]
ok. Just so you all know, it might not be worth the effort of trying to get into my discord server. There are many hoops, partially by design, partially by my incompetence.
