### ISSUE TITLE
Future of the Project

### ISSUE THREAD

**Issue by colbsmcdolbs** [riverscuomo/new-albums#23]
Leaving this issue as more of a question.

What is the proposed future of this project? Are there any features or enhancements that have been proposed?

I was wondering if we could possibly make a front end that could consume this script as a service that would allow users to be able to login and run the script without having to setup everything locally on their machine.

Wanting to contribute to this project, but not sure what the roadmap is.

Thanks!

**Comment by riverscuomo** [comment]
Yeah I was thinking something like that. But before we dive in, let me add another project to GitHub. It's similar to this one but actually a lot cooler.  And the two are related so may share some resources. I'll hopefully commit it tomorrow.  Just gotta remove all the secrets. 
It was called 'new_music' but I think I'll upload it as 'spotMasher'.

**Comment by colbsmcdolbs** [comment]
Very nice. Sounds good!

Also, have you been committing locally with the secrets? If so, it might be better to reinitialize the Git repo before pushing, so they won't live in the Git history.

Source: Have made that mistake before.

**Comment by riverscuomo** [comment]
I've made that mistake before too. 
I just initialized the new project repository and shared it on GitHub as 'spotnik'
https://github.com/riverscuomo/spotnik

**Comment by colbsmcdolbs** [comment]
@riverscuomo Wanted to let you know that my wife and I are gonna be at your show in Boise this weekend. Super excited for it!

**Comment by GCJ2** [comment]
@colbsmcdolbs Did you guys have a good time?
cc @riverscuomo
